"""Add proficiency to candidate_skills

Revision ID: 1e5646676071
Revises: d93bc9ef6c65
Create Date: 2025-05-20 23:49:54.235001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5646676071'
down_revision: Union[str, None] = 'd93bc9ef6c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_profiles_fisrt_name', table_name='candidate_profiles')
    op.drop_index('ix_candidate_profiles_last_name', table_name='candidate_profiles')
    op.drop_index('ix_candidate_profiles_phone_number', table_name='candidate_profiles')
    op.drop_index('ix_candidate_profiles_user_id', table_name='candidate_profiles')
    op.create_unique_constraint(None, 'candidate_profiles', ['user_id'])
    op.drop_column('candidate_profiles', 'last_name')
    op.drop_column('candidate_profiles', 'fisrt_name')
    op.add_column('candidate_skills', sa.Column('proficiency', sa.String(), nullable=True))
    op.drop_index('ix_candidate_skills_candidate_profile_id', table_name='candidate_skills')
    op.drop_column('candidate_skills', 'proficiency_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_skills', sa.Column('proficiency_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_candidate_skills_candidate_profile_id', 'candidate_skills', ['candidate_profile_id'], unique=False)
    op.drop_column('candidate_skills', 'proficiency')
    op.add_column('candidate_profiles', sa.Column('fisrt_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('candidate_profiles', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'candidate_profiles', type_='unique')
    op.create_index('ix_candidate_profiles_user_id', 'candidate_profiles', ['user_id'], unique=True)
    op.create_index('ix_candidate_profiles_phone_number', 'candidate_profiles', ['phone_number'], unique=True)
    op.create_index('ix_candidate_profiles_last_name', 'candidate_profiles', ['last_name'], unique=False)
    op.create_index('ix_candidate_profiles_fisrt_name', 'candidate_profiles', ['fisrt_name'], unique=False)
    # ### end Alembic commands ###
