"""add_candidate_profile_experience_education_skill_tables

Revision ID: 57bb75aeeb2c
Revises: acbe1438235c
Create Date: 2025-05-16 15:37:01.082474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bb75aeeb2c'
down_revision: Union[str, None] = 'acbe1438235c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
