"""fix_typo_fisrt_name_in_candidate_profile

Revision ID: 5c920583eaa0
Revises: 6ee981ab36f2
Create Date: 2025-05-19 20:28:21.983883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c920583eaa0'
down_revision: Union[str, None] = '6ee981ab36f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
